/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Controller Base-URL": { "en": "Controller Base-URL", "de": "URL der Poolsteuerung", "ru": "Controller Base-URL", "pt": "Controller Base-URL", "nl": "Controller Base-URL", "fr": "Controller Base-URL", "it": "Controller Base-URL", "es": "Controller Base-URL", "pl": "Controller Base-URL", "zh-cn": "Controller Base-URL" },
    "Password": { "en": "Password", "de": "Passwort", "ru": "Password", "pt": "Password", "nl": "Password", "fr": "Password", "it": "Password", "es": "Password", "pl": "Password", "zh-cn": "Password" },
    "Please choose a value smaller than 86400000(ms = 24h).": { "en": "Please choose a value smaller than 86400000(ms = 24h).", "de": "Bitte wählen Sie einen Wert kleiner als 86400000 (ms = 24h).", "ru": "Пожалуйста, выберите значение меньше 86400000 (мс = 24 ч).", "pt": "Por favor, escolha um valor menor que 86400000 (ms = 24h).", "nl": "Kies een waarde kleiner dan 86400000 (ms = 24 uur).", "fr": "Veuillez choisir une valeur inférieure à 86400000 (ms = 24h).", "it": "Scegli un valore inferiore a 86400000 (ms = 24h).", "es": "Elija un valor menor que 86400000 (ms = 24h).", "pl": "Wybierz wartość mniejszą niż 86400000 (ms = 24h).", "zh-cn": "请选择小于86400000（ms = 24h）的值。" },
    "Please enter a valid url including the 'http' or 'https'.": { "en": "Please enter a valid url including the 'http' or 'https'.", "de": "Bitte geben Sie eine gültige URL ein, einschließlich \"http\" oder \"https\".", "ru": "Пожалуйста, введите действительный URL, включая «http» или «https».", "pt": "Digite um URL válido, incluindo o 'http' ou 'https'.", "nl": "Voer een geldige URL in, inclusief 'http' of 'https'.", "fr": "Veuillez saisir une URL valide comprenant le \"http\" ou le \"https\".", "it": "Inserisci un URL valido che includa \"http\" o \"https\".", "es": "Ingrese una URL válida que incluya 'http' o 'https'.", "pl": "Wprowadź prawidłowy adres URL, w tym „http” lub „https”.", "zh-cn": "请输入有效的网址，包括“ http”或“ https”。" },
    "Please keep it reasonably plausible and stay between 500(ms) and 86400000(ms = 24h).": {
        "en": "Please keep it reasonably plausible and stay between 500(ms) and 86400000(ms = 24h).",
        "de": "Bitte halten Sie es einigermaßen plausibel und bleiben Sie zwischen 500 (ms) und 86400000 (ms = 24h).",
        "ru": "Пожалуйста, оставьте его достаточно правдоподобным и оставайтесь в пределах от 500 (мс) до 86400000 (мс = 24 часа).",
        "pt": "Mantenha-o razoavelmente plausível e fique entre 500 (ms) e 86400000 (ms = 24h).",
        "nl": "Houd het redelijk aannemelijk en blijf tussen 500 (ms) en 86400000 (ms = 24 uur).",
        "fr": "Veuillez le garder raisonnablement plausible et rester entre 500 (ms) et 86400000 (ms = 24h).",
        "it": "Tienilo ragionevolmente plausibile e rimani tra 500 (ms) e 86400000 (ms = 24h).",
        "es": "Manténgalo razonablemente plausible y entre 500 (ms) y 86400000 (ms = 24 h).",
        "pl": "Proszę zachować rozsądną wiarygodność i pozostać między 500 (ms) a 86400000 (ms = 24h).",
        "zh-cn": "请使其合理合理，并保持在500（ms）至86400000（ms = 24h）之间。"
    },
    "Please keep the value above 100(ms).": { "en": "Please keep the value above 100(ms).", "de": "Bitte halten Sie den Wert über 100 (ms).", "ru": "Пожалуйста, сохраняйте значение выше 100 (мс).", "pt": "Mantenha o valor acima de 100 (ms).", "nl": "Houd de waarde boven 100 (ms).", "fr": "Veuillez conserver la valeur au-dessus de 100 (ms).", "it": "Si prega di mantenere il valore superiore a 100 (ms).", "es": "Mantenga el valor por encima de 100 (ms).", "pl": "Proszę utrzymać wartość powyżej 100 (ms).", "zh-cn": "请将该值保持在100（ms）以上。" },
    "The url you have entered does not start with 'http://' or 'https://'": { "en": "The url you have entered does not start with 'http://' or 'https://'", "de": "Die von Ihnen eingegebene URL beginnt nicht mit \"http: //\" oder \"https: //\".", "ru": "Введенный вами URL не начинается с «http: //» или «https: //»", "pt": "O URL digitado não começa com 'http: //' ou 'https: //'", "nl": "De url die je hebt ingevoerd begint niet met 'http: //' of 'https: //'", "fr": "L'URL que vous avez saisie ne commence pas par «http: //» ou «https: //»", "it": "L'URL inserito non inizia con 'http: //' o 'https: //'", "es": "La url que ha ingresado no comienza con 'http: //' o 'https: //'", "pl": "Wprowadzony adres URL nie zaczyna się od „http: //” ani „https: //”", "zh-cn": "您输入的网址不是以“ http：//”或“ https：//”开头" },
    "Update interval (ms)": { "en": "Update interval (ms)", "de": "Update-Interval (ms)", "ru": "Update interval (ms)", "pt": "Update interval (ms)", "nl": "Update interval (ms)", "fr": "Update interval (ms)", "it": "Update interval (ms)", "es": "Update interval (ms)", "pl": "Update interval (ms)", "zh-cn": "Update interval (ms)" },
    "Use basic auth": { "en": "Use basic auth", "de": "Authentifizierung benutzen (HTTP Basic Auth)", "ru": "Use basic auth", "pt": "Use basic auth", "nl": "Use basic auth", "fr": "Use basic auth", "it": "Use basic auth", "es": "Use basic auth", "pl": "Use basic auth", "zh-cn": "Use basic auth" },
    "Username": { "en": "Username", "de": "Benutzername", "ru": "Username", "pt": "Username", "nl": "Username", "fr": "Username", "it": "Username", "es": "Username", "pl": "Username", "zh-cn": "Username" },
    "Request timeout (ms)": {
        "en": "Request timeout (ms)",
        "de": "Zeitüberschreitung anfordern (ms)",
        "ru": "Тайм-аут запроса (мс)",
        "pt": "Solicitar tempo limite (ms)",
        "nl": "Time-out verzoek (ms)",
        "fr": "Délai d'expiration de la demande (ms)",
        "it": "Richiedi timeout (ms)",
        "es": "Solicitar tiempo de espera (ms)",
        "pl": "Limit czasu żądania (ms)",
        "zh-cn": "请求超时（毫秒）"
    },
    "Please keep it reasonably plausible and stay between 500(ms) and 60000(ms = 60s = 1min).": {
        "en": "Please keep it reasonably plausible and stay between 500(ms) and 60000(ms = 60s = 1min).",
        "de": "Bitte halten Sie es einigermaßen plausibel und bleiben Sie zwischen 500 (ms) und 60000 (ms = 60s = 1min).",
        "ru": "Пожалуйста, оставьте его достаточно правдоподобным и оставайтесь в пределах от 500 (мс) до 60000 (мс = 60 с = 1 мин).",
        "pt": "Mantenha-o razoavelmente plausível e fique entre 500 (ms) e 60000 (ms = 60s = 1min).",
        "nl": "Houd het redelijk aannemelijk en blijf tussen 500 (ms) en 60000 (ms = 60s = 1min).",
        "fr": "Veuillez le garder raisonnablement plausible et rester entre 500 (ms) et 60000 (ms = 60s = 1min).",
        "it": "Si prega di mantenerlo ragionevolmente plausibile e di rimanere tra 500 (ms) e 60000 (ms = 60 s = 1 min).",
        "es": "Por favor, manténgalo razonablemente plausible y entre 500 (ms) y 60000 (ms = 60s = 1min).",
        "pl": "Proszę zachować rozsądną wiarygodność i pozostawać pomiędzy 500 (ms) a 60000 (ms = 60s = 1min).",
        "zh-cn": "请使其合理合理，并保持在500（ms）至60000（ms = 60s = 1min）之间。"
    },
    "Please keep the value greater or equal 500(ms).": {
        "en": "Please keep the value greater or equal 500(ms).",
        "de": "Bitte halten Sie den Wert größer oder gleich 500 (ms).",
        "ru": "Пожалуйста, оставьте значение больше или равным 500 (мс).",
        "pt": "Mantenha o valor maior ou igual a 500 (ms).",
        "nl": "Houd de waarde groter of gelijk aan 500 (ms).",
        "fr": "Veuillez conserver la valeur supérieure ou égale à 500 (ms).",
        "it": "Si prega di mantenere il valore maggiore o uguale a 500 (ms).",
        "es": "Mantenga el valor mayor o igual a 500 (ms).",
        "pl": "Zachowaj wartość większą lub równą 500 (ms).",
        "zh-cn": "请保持该值大于或等于500（ms）。"
    },
    "Please choose a value lesser or equal 60000(ms = 60s).": {
        "en": "Please choose a value lesser or equal 60000(ms = 60s).",
        "de": "Bitte wählen Sie einen Wert kleiner oder gleich 60000 (ms = 60s).",
        "ru": "Выберите значение, меньшее или равное 60000 (мс = 60 с).",
        "pt": "Escolha um valor menor ou igual a 60000 (ms = 60s).",
        "nl": "Kies een waarde kleiner dan of gelijk aan 60000 (ms = 60s).",
        "fr": "Veuillez choisir une valeur inférieure ou égale à 60000 (ms = 60s).",
        "it": "Scegli un valore inferiore o uguale a 60000 (ms = 60 s).",
        "es": "Elija un valor menor o igual a 60000 (ms = 60 s).",
        "pl": "Wybierz wartość mniejszą lub równą 60000 (ms = 60s).",
        "zh-cn": "请选择一个小于或等于60000（ms = 60s）的值。"
    },
    "Max tolerable errors": {
        "en": "Max tolerable errors",
        "de": "Max tolerierbare Fehler",
        "ru": "Максимально допустимые ошибки",
        "pt": "Máximo de erros toleráveis",
        "nl": "Max. Toelaatbare fouten",
        "fr": "Erreurs tolérables maximales",
        "it": "Max errori tollerabili",
        "es": "Errores máximos tolerables",
        "pl": "Maksymalna dopuszczalna liczba błędów",
        "zh-cn": "最大容许误差"
    },
    "Define after how many consecutively failed requests as warning will be logged.": {
        "en": "Define after how many consecutively failed requests as warning will be logged.",
        "de": "Legen Sie fest, nach wie vielen nacheinander fehlgeschlagenen Anforderungen als Warnung protokolliert wird.",
        "ru": "Определите, после скольких последовательно неудачных запросов будет регистрироваться предупреждение.",
        "pt": "Defina depois de quantas solicitações consecutivas com falha, pois o aviso será registrado.",
        "nl": "Geef aan na hoeveel opeenvolgende mislukte verzoeken als waarschuwing worden geregistreerd.",
        "fr": "Définissez après combien de demandes ayant échoué consécutivement, les avertissements seront enregistrés.",
        "it": "Definire dopo quante richieste consecutivamente non riuscite verranno registrate le avvertenze.",
        "es": "Defina después de cuántas solicitudes fallidas consecutivamente como advertencia se registrarán.",
        "pl": "Określ, po ilu kolejnych nieudanych żądaniach będą rejestrowane ostrzeżenia.",
        "zh-cn": "定义将记录多少连续失败的警告请求后。"
    },
    "Please keep the value greater or equal 2.": {
        "en": "Please keep the value greater or equal 2.",
        "de": "Bitte halten Sie den Wert größer oder gleich 2.",
        "ru": "Пожалуйста, оставьте значение больше или равным 2.",
        "pt": "Mantenha o valor maior ou igual a 2.",
        "nl": "Houd de waarde groter of gelijk aan 2.",
        "fr": "Veuillez garder la valeur supérieure ou égale à 2.",
        "it": "Si prega di mantenere il valore maggiore o uguale a 2.",
        "es": "Mantenga el valor mayor o igual a 2.",
        "pl": "Zachowaj wartość większą lub równą 2.",
        "zh-cn": "请保持该值大于或等于2。"
    },
    "Please choose a value greater or equal 1000.": {
        "en": "Please choose a value greater or equal 1000.",
        "de": "Bitte wählen Sie einen Wert größer oder gleich 1000.",
        "ru": "Выберите значение больше или равное 1000.",
        "pt": "Escolha um valor maior ou igual a 1000.",
        "nl": "Kies een waarde groter dan of gelijk aan 1000.",
        "fr": "Veuillez choisir une valeur supérieure ou égale à 1000.",
        "it": "Scegli un valore maggiore o uguale a 1000.",
        "es": "Elija un valor mayor o igual a 1000.",
        "pl": "Wybierz wartość większą lub równą 1000.",
        "zh-cn": "请选择一个大于或等于1000的值。"
    },
};