/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Controller Base-URL": {                         "en": "Controller Base-URL",                             "de": "URL der Poolsteuerung",                           "ru": "Controller Base-URL",                             "pt": "Controller Base-URL",                             "nl": "Controller Base-URL",                             "fr": "Controller Base-URL",                             "it": "Controller Base-URL",                             "es": "Controller Base-URL",                             "pl": "Controller Base-URL",                             "zh-cn": "Controller Base-URL"},
    "Use basic auth": {                              "en": "Use basic auth",                                  "de": "Authentifizierung benutzen (HTTP Basic Auth)",    "ru": "Use basic auth",                                  "pt": "Use basic auth",                                  "nl": "Use basic auth",                                  "fr": "Use basic auth",                                  "it": "Use basic auth",                                  "es": "Use basic auth",                                  "pl": "Use basic auth",                                  "zh-cn": "Use basic auth"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "Username",                                        "pt": "Username",                                        "nl": "Username",                                        "fr": "Username",                                        "it": "Username",                                        "es": "Username",                                        "pl": "Username",                                        "zh-cn": "Username"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Password",                                        "pt": "Password",                                        "nl": "Password",                                        "fr": "Password",                                        "it": "Password",                                        "es": "Password",                                        "pl": "Password",                                        "zh-cn": "Password"},
    "Update interval (ms)": {                        "en": "Update interval (ms)",                            "de": "Update-Interval (ms)",                            "ru": "Update interval (ms)",                            "pt": "Update interval (ms)",                            "nl": "Update interval (ms)",                            "fr": "Update interval (ms)",                            "it": "Update interval (ms)",                            "es": "Update interval (ms)",                            "pl": "Update interval (ms)",                            "zh-cn": "Update interval (ms)"},
};