/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Controller Base-URL": {                         "en": "Controller Base-URL",                             "de": "URL der Poolsteuerung",                           "ru": "Controller Base-URL",                             "pt": "Controller Base-URL",                             "nl": "Controller Base-URL",                             "fr": "Controller Base-URL",                             "it": "Controller Base-URL",                             "es": "Controller Base-URL",                             "pl": "Controller Base-URL",                             "zh-cn": "Controller Base-URL"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Password",                                        "pt": "Password",                                        "nl": "Password",                                        "fr": "Password",                                        "it": "Password",                                        "es": "Password",                                        "pl": "Password",                                        "zh-cn": "Password"},
    "Update interval (ms)": {                        "en": "Update interval (ms)",                            "de": "Update-Interval (ms)",                            "ru": "Update interval (ms)",                            "pt": "Update interval (ms)",                            "nl": "Update interval (ms)",                            "fr": "Update interval (ms)",                            "it": "Update interval (ms)",                            "es": "Update interval (ms)",                            "pl": "Update interval (ms)",                            "zh-cn": "Update interval (ms)"},
    "Use basic auth": {                              "en": "Use basic auth",                                  "de": "Authentifizierung benutzen (HTTP Basic Auth)",    "ru": "Use basic auth",                                  "pt": "Use basic auth",                                  "nl": "Use basic auth",                                  "fr": "Use basic auth",                                  "it": "Use basic auth",                                  "es": "Use basic auth",                                  "pl": "Use basic auth",                                  "zh-cn": "Use basic auth"},
    "Username": {                                    "en": "Username",                                        "de": "Benutzername",                                    "ru": "Username",                                        "pt": "Username",                                        "nl": "Username",                                        "fr": "Username",                                        "it": "Username",                                        "es": "Username",                                        "pl": "Username",                                        "zh-cn": "Username"},
    "Please enter a valid url including the 'http' or 'https'.": {"en": "Please enter a valid url including the 'http' or 'https'.", "de": "Bitte geben Sie eine gültige URL ein, einschließlich \"http\" oder \"https\".", "ru": "Пожалуйста, введите действительный URL, включая «http» или «https».", "pt": "Digite um URL válido, incluindo o 'http' ou 'https'.", "nl": "Voer een geldige URL in, inclusief 'http' of 'https'.", "fr": "Veuillez saisir une URL valide comprenant le \"http\" ou le \"https\".", "it": "Inserisci un URL valido che includa \"http\" o \"https\".", "es": "Ingrese una URL válida que incluya 'http' o 'https'.", "pl": "Wprowadź prawidłowy adres URL, w tym „http” lub „https”.", "zh-cn": "请输入有效的网址，包括“ http”或“ https”。"},
    "The url you have entered does not start with 'http://' or 'https://'": {"en": "The url you have entered does not start with 'http://' or 'https://'", "de": "Die von Ihnen eingegebene URL beginnt nicht mit 'http: //' oder 'https: //'.", "ru": "Введенный вами URL не начинается с «http: //» или «https: //»", "pt": "O URL digitado não começa com 'http: //' ou 'https: //'", "nl": "De url die je hebt ingevoerd begint niet met 'http: //' of 'https: //'", "fr": "L'URL que vous avez saisie ne commence pas par «http: //» ou «https: //»", "it": "L'URL inserito non inizia con 'http: //' o 'https: //'", "es": "La url que ha ingresado no comienza con 'http: //' o 'https: //'", "pl": "Wprowadzony adres URL nie zaczyna się od „http: //” ani „https: //”", "zh-cn": "您输入的网址不是以“ http：//”或“ https：//”开头"},
    "Please keep it reasonably plausible and stay between 100(ms) and 86400000(ms = 24h).": {"en": "Please keep it reasonably plausible and stay between 100(ms) and 86400000(ms = 24h).", "de": "Bitte halten Sie es einigermaßen plausibel und bleiben Sie zwischen 100 (ms) und 86400000 (ms = 24h).", "ru": "Пожалуйста, держите это разумно правдоподобным и оставайтесь между 100 (мс) и 86400000 (мс = 24 ч).", "pt": "Mantenha-o razoavelmente plausível e fique entre 100 (ms) e 86400000 (ms = 24h).", "nl": "Houd het redelijk aannemelijk en blijf tussen 100 (ms) en 86400000 (ms = 24u).", "fr": "Veuillez le garder raisonnablement plausible et rester entre 100 (ms) et 86400000 (ms = 24h).", "it": "Si prega di tenerlo ragionevolmente plausibile e rimanere tra 100 (ms) e 86400000 (ms = 24h).", "es": "Manténgalo razonablemente plausible y manténgase entre 100 (ms) y 86400000 (ms = 24h).", "pl": "Zachowaj rozsądną wiarygodność i pozostań między 100 (ms) a 86400000 (ms = 24h).", "zh-cn": "请使其合理合理，并保持在100（ms）到86400000（ms = 24h）之间。"},
    "Please keep the value above 100(ms).": {        "en": "Please keep the value above 100(ms).",            "de": "Bitte halten Sie den Wert über 100 (ms).",        "ru": "Пожалуйста, сохраняйте значение выше 100 (мс).",  "pt": "Mantenha o valor acima de 100 (ms).",             "nl": "Houd de waarde boven 100 (ms).",                  "fr": "Veuillez conserver la valeur au-dessus de 100 (ms).", "it": "Si prega di mantenere il valore superiore a 100 (ms).", "es": "Mantenga el valor por encima de 100 (ms).",       "pl": "Proszę utrzymać wartość powyżej 100 (ms).",       "zh-cn": "请将该值保持在100（ms）以上。"},
    "Please choose a value smaller than 86400000(ms = 24h).": {"en": "Please choose a value smaller than 86400000(ms = 24h).", "de": "Bitte wählen Sie einen Wert kleiner als 86400000 (ms = 24h).", "ru": "Пожалуйста, выберите значение меньше 86400000 (мс = 24 ч).", "pt": "Por favor, escolha um valor menor que 86400000 (ms = 24h).", "nl": "Kies een waarde kleiner dan 86400000 (ms = 24 uur).", "fr": "Veuillez choisir une valeur inférieure à 86400000 (ms = 24h).", "it": "Scegli un valore inferiore a 86400000 (ms = 24h).", "es": "Elija un valor menor que 86400000 (ms = 24h).",   "pl": "Wybierz wartość mniejszą niż 86400000 (ms = 24h).", "zh-cn": "请选择小于86400000（ms = 24h）的值。"},
};